Set C++ standard version to 14
This is required by GCC for return type deduction:

	src/shell/main.cpp:89:91: error: ‘run’ function uses ‘auto’ type specifier without trailing return type
	 auto run(const std::wstring& config_file_name, std::atomic<bool>& should_wait_for_keypress)
	                                                                                           ^
	src/shell/main.cpp:89:91: note: deduced return type only available with -std=c++14 or -std=gnu++14